# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docentes',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=60)),
                ('area_saber', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=13)),
                ('correo', models.EmailField(max_length=100)),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('cedula_est', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nombre_est', models.CharField(max_length=40)),
                ('apellido_est', models.CharField(max_length=60)),
                ('seccion', models.CharField(max_length=4)),
                ('trayecto', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=4)),
                ('trimestre', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=4)),
                ('id_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstApp.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstApp.estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proy', models.TextField(max_length=300)),
                ('id_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstApp.grupo')),
            ],
        ),
    ]
