# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='num_grupo',
            field=models.IntegerField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
