# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pstApp', '0004_auto_20170804_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='comunidad_institucion',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='municipio',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
