# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pstApp', '0005_auto_20170808_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='avances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadrevisada', models.TextField(max_length=1200)),
                ('actividadasignada', models.TextField(max_length=1200)),
                ('observaciones', models.TextField(max_length=1200)),
                ('fechaproxentrega', models.DateField()),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pstApp.proyecto')),
            ],
        ),
    ]
